export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';
export const ADD_FETCHED_CATEGORY = 'ADD_FETCHED_CATEGORY';
export const SEARCH_OPTIONS = 'SEARCH_OPTIONS';
export const FETCH_CART = 'FETCH_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
